### ISSUE TITLE
Summary generation

### ISSUE THREAD

**Issue by ratsclub** [mdzk-rs/mdzk#1]
Add a command to generate the summary based on the files.

Should we handle subdirectories as hierarchy?

Consider the following directory structure:
```
/file.md
/directory/file.md
```

Should we render it as the following?

```md
- [title](./file.md)
- [directory]()
  - [title](./directory/file.md)
```

**Comment by kmaasrud** [comment]
Your really awesome solution is added in dc711a3a66bf5a3e140b7e278f85585aa550fced! It works great on my vault, and uses your proposed solution of

> ```
> - [title](./file.md)
> - [directory]()
>   - [title](./directory/file.md)
> ```

I keep a completely flat structure in my vault, so I'm not able to properly test if nested directories work. I know you use sub-directories in your vault, @ratsclub, so could you run a quick test before we close this issue?

**Comment by ratsclub** [comment]
Everything looks fine so far. Closing this issue.
