### ISSUE TITLE
RSS or Atom feed functionality

### ISSUE THREAD

**Issue by ojn** [mdzk-rs/mdzk#19]
It would be great if mdzk could have a feed for recently modified pages. That can be useful when other people want to subscribe to your notes. 

There's this preprocessor for mdBook [mdbook-rss](https://gitlab.com/albalitz/mdbook-rss) I have not tried it myself though, not sure how much work it would need. This one uses `pub_date` in front matter to order the articles.

**Comment by kmaasrud** [comment]
That is such a cool idea! Quickly scanning mdbook-rss, I think it might not be perfect for our purposes, but we could leave some MRs on the repo or simply make our own preprocessor based on it.

Thanks for the suggestion! We will definitely consider adding this soon :smile:

**Comment by kmaasrud** [comment]
Closing due to new visions for mdzk 1.0.0
