### ISSUE TITLE
Toggle enabling regular markdown-links to function as internal

### ISSUE THREAD

**Issue by michael-ames** [mdzk-rs/mdzk#25]
Does this support regular markdown link syntax?
`[link text](./filename.md)`

Many of my source files have links in this format that aren't being picked up as backlinks. 

If not supported currently, looks like I'd want to edit the regex [here](https://github.com/mdzk-rs/mdbook-backlinks/blob/main/src/lib.rs#L84), right?

**Comment by michael-ames** [comment]
Thanks!

**Comment by kmaasrud** [comment]
Reopening, so we can keep track of the toggle feature with this issue

**Comment by kmaasrud** [comment]
The next generation mdzk will make a hard distinction between regular links and internal links (wikilinks), meaning this issue will not be adressed. Closing.
