### ISSUE TITLE
[feature] Option to use a custom HTTP port for the serve command

### ISSUE THREAD

**Issue by lucasew** [mdzk-rs/mdzk#3]
3000 is a port often used for dev servers like CRA and NextJS and it's a bit frustrating to have to stop the dev server to load this app's server.

Another behavior that can be useful for a lot of people is that if the app fails to bind to the default port if unspecified then try to bind the next one.

If the default port is 3000 and fails to bind now it just crashes but it should try 3001 and so on. Would be a great differential!

**Comment by kmaasrud** [comment]
Thanks for the feature suggestion @lucasew  😃
