### ISSUE TITLE
Linking to images?

### ISSUE THREAD

**Issue by alanmbarr** [mdzk-rs/mdzk#44]
I'm not sure if I am using the library correctly. When I insert a wikilink to an image the output is noted in mdzk as a missing link. You can see an example [here](https://notes.alanmbarr.com/Various%20Thoughts/Wardley%20Maps.html).

For now I am hard coding img tags. Am I doing something incorrect or the syntax is different? It works in obsidian but when I publish it doesn't come out as knowing about the image.
```
![[Bins/Images/WardleyMapBlank.png]]
 [![[Bins/Images/Wardley_Pioneers-Settlers-Town_Planners.jpg]]](https://blog.gardeviance.org/2015/04/the-only-structure-youll-ever-need.html)

<img src="/Bins/Images/Wardley_Pioneers-Settlers-Town_Planners.jpg">
```

**Comment by ratsclub** [comment]
Unfortunately, this syntax is currently not supported... However, we intend to implement it in the future!

In the mean time you can use regular markdown linkings `!["Image caption"](image.jpg)`.

**Comment by kmaasrud** [comment]
Also note that regular markdown images work, but the images will not get copied over to the output directory, so you will have to do this manually. This is also firmly on the todo-list, so stay tuned for full image support in the near future.

**Comment by alanmbarr** [comment]
Great thanks for the answers cleared up whether I was simply using it wrong. I'm excited about this project.

**Comment by ratsclub** [comment]
Note that by using regular markdown the image is copied over to the output directory just as expected.

**Comment by morgenman** [comment]
This is a very ugly solution, but I fixed this by preprocessing my md files (gh actions) before running mdzk:
```yml
      - name: images
        run: |
          mkdir ./notes/assets/
          find ./_notes/ -name '*.jpg' -exec mv {} ./notes/assets/ \;
          find ./_notes/ -name '*.png' -exec mv {} ./notes/assets/ \;
          find ./_notes/ -name '*.svg' -exec mv {} ./notes/assets/ \;
          find ./_notes/ -name '*.pdf' -exec mv {} ./notes/assets/ \;
          find ./_notes/ -name '*.ppt' -exec mv {} ./notes/assets/ \;
          find ./_notes/ -name '*.md' | while read -r i; do  x=`sed -E "s~![[][[]([^.]*)\.(png|jpg|svg)]]~<a href=\"https://morgenman.github.io/Computer-Science/assets/\1.\2\" target=\"_blank\"><img src=\"https://morgenman.github.io/Computer-Science/assets/\1.\2\" alt=\"\1\"/></a>\n~g" "$i"` && echo "$x" > "$i"; done
          find ./_notes/ -name '*.md' | while read -r i; do  x=`sed -E "s|!*[[][[]([^.]*)\.([^]]*)]]|<a href=\"https://morgenman.github.io/Computer-Science/assets/\1.\2\">\1.\2</a>\n|g" "$i"` && echo "$x" > "$i"; done
```
Obviously this has some hardcoded URLs, but it results in working attachment and image links. 
It's designed for github actions, but should work if you put it in a batch file too, assuming you are running on linux. 
I have similarly fixed references to [[mainNote#subsection]] and [[Note|alias]], which seem to not work out of box.

**Comment by kmaasrud** [comment]
We will try to interfere as little as possible with CommonMark, and will thus stick with the conventional embed syntax for images instead of implementing Obsidian's image embeds.
