### ISSUE TITLE
Without Frontmatter, first header is not styled

### ISSUE THREAD

**Issue by morgenman** [mdzk-rs/mdzk#58]
I have noticed that for md files like the following, the first header will not be rendered:
```md
# Header 1
somecontent
# Header 2
```
This is fixed if moved to any line that is not the first line (I am inserting a blank newline before line 1 to fix it). 
I think the assumption here was that every md file would have some sort of frontmatter, which most of my notes do not. 
Is this expected behavior?

**Comment by kmaasrud** [comment]
Is the snippet you supplied verbatim? If so, then it is not valid CommonMark... Headers require a blank newline immediately below them, and while I think it renders correctly in some cases, it might fuck with our preprocessors...

Could you try disabling the front matter preprocessor and see if that fixes the issue? If so, then our front matter parser might be the culprit and I'll submit a PR there. You can disable front matter on mdzk HEAD by adding

```toml
[build]
#...
front-matter = false
```

in the config.

Thanks for noticing this :smile:

**Comment by kmaasrud** [comment]
I just tried to reproduce your issue, but by pasting your snippet in a test note, I get the following:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/54394333/142719990-74385472-51eb-4131-97ee-fedec25dd9ac.png">

In other words, it renders as expected. Are you including all the content of your note? I'm also not running version 0.4.3, but a version built from upstream. Are you running 0.4.3?
