### ISSUE TITLE
Move around some of the configuration options

### ISSUE THREAD

**Issue by kmaasrud** [mdzk-rs/mdzk#68]
This sadly has to be done because some options logically belong to other tables. These need to be moved:

- `ignore` from `[mdzk]` to `[build]`
- `backlinks-header` from `[mdzk]` to `[style]`
- `generate-summary` from `[mdzk]` to `[build]`
- Fold options from `[output.html]` to `[style]`

**Comment by huangziwei** [comment]
sorry if this is a wrong place to ask, but how can I turn on the search functionality? I am using 0.5.0 currently.

**Comment by kmaasrud** [comment]
@huangziwei sorry about that! I managed to remove the search functionality by accident on 0.5.0, but this is fixed in 0.5.1 which we will release very soon, so stay tuned for that! I will ping you when that happens :smile:

**Comment by kmaasrud** [comment]
@huangziwei 0.5.1 is live now!

**Comment by huangziwei** [comment]
Thanks for the update! I have a few questions regarding to the new [style] section.

1. when using `css='''<css>'''`, the generated css in the user.css shows: ```:root { --css: className {...}}``` . In the note I have a HTML tag with class="className", but it doesn't seem working. But I am actually not very familiar with :root or -- variable.
2. Is the dark theme gone now? or should it be configured in the [style] section?

**Comment by huangziwei** [comment]
btw, the search doesn't work on Chinese and Japanese...

**Comment by kmaasrud** [comment]
1. That's a typo in the release notes! It's supposed to be `additional-css`. Try changing to that and it should work smoothly.
2. The dark theme is gone, yes... We rewrote the page template completely from scratch, and adding a theme toggle seemed unecessary with the idea of giving the user access to the CSS variables. Try e.g. setting `fg = "white"`, `bg = "black" `, etc. to make your own theme if you want! You can see all variables by using the inspect tool in your browser.
3. The search only works in english, sadly... Other languages require huge dictionary assets, which would make the binary very bloated. Try setting the language to english and see if the search works without the assets.

**Comment by huangziwei** [comment]
Although I takes notes mainly in English, I do still use Chinese and Japanese occasionally if the books I read are in those languages... maybe you can add a functionality to add dictionaries for additional languages by users?

**Comment by kmaasrud** [comment]
The next version of mdzk will not be an SSG, but rather a general purpose interface for parsing a Zettelkasten into a directed graph. This will let users easily create their own publishing workflows (e.g. with something like Hugo), integrate into their editors and more. We will supply our own SSG as well, mirroring the one we have now, and I'll definitely look further into supporting multiple languages in the search!

All of this is to say that chinese/japanese search will probably not arrive until we are done with the rewrite, I'm sorry. I'll open a separate issue for it though, so you can track the feature there :smile:

**Comment by kmaasrud** [comment]
Issue no longer relevant to the next generation mdzk. Closing.
