### ISSUE TITLE
Parentheses in note title is not parsed

### ISSUE THREAD

**Issue by huangziwei** [mdzk-rs/mdzk#70]
For example, a note with a title `How to Take Smart Notes (2017) by Sönke Ahrens` was referred in another note as `[[How to Take Smart Notes (2017) by Sönke Ahrens]]`, but it is parsed as `<span class="missing-link" style="color:darkred;">How to Take Smart Notes</span>` in the HTML generated by `mdzk`.

**Comment by kmaasrud** [comment]
First, I apologize for the really late reply!

This is weird, parentheses should be working. I'll try to reproduce your issue, make a test case for it and see if there is an issue in our link parsing.

In the meantime: We just released mdzk 0.5.1, which includes a lot of changes and fixes. Could you check against it and see if your problem persists?

**Comment by huangziwei** [comment]
@kmaasrud just tried 0.5.1 and the problem persists.

**Comment by kmaasrud** [comment]
Allright, thanks for checking :smile:

We might not do a whole new release with a patch for this, as we are changing quite a lot with how mdzk works atm. However, I can see if I find the culprit and push the fixes, so that you can install from upstream! Will keep you posted

**Comment by huangziwei** [comment]
No problem. I already adapted to the tool and now use "Author - YEAR - TITLE" as note title. :-)

**Comment by kmaasrud** [comment]
This was apparently caused by a logical error in our parser grammar. By compiling from HEAD with a command like `cargo install --git https://github.com/mdzk-rs/mdzk`, links with parentheses or curly brackets should now work.

**Comment by kmaasrud** [comment]
FYI, the fix is included in 0.5.2 which was just released!
