### ISSUE TITLE
Theming built HTML website

### ISSUE THREAD

**Issue by wylited** [mdzk-rs/mdzk#74]
I had recently changed laptops, and therefore updated my mdzk version. I have a folder called ./themes/ in the same directory as the mdzk.toml file. However this version no longer seems to respect the css and javascript (./themes/css/main.css, ./themes/css/variables.css, etc.) in the themes folder and uses the default customization for the website.
How would I fix this?

**Comment by kmaasrud** [comment]
You can no longer customize your mdzk site with the `theme` directory, like in mdBook. See the [changelog](https://github.com/mdzk-rs/mdzk/blob/main/CHANGELOG.md#051-2022-02-21) for details.

We built a custom renderer completely from scratch, and thus had to make a few decisions for how users could style their site. We found the `theme` dir to be overkill and that allowing CSS customization through the configuration file would feel more natural.
